#+STARTUP: indent
#+OPTIONS: toc:nil num:nil
#+TITLE: ECON 497 Assignment 1
#+LaTeX_CLASS_OPTIONS: [article,letterpaper,times,10pt,margin=0.7in]
#+LATEX_HEADER: \usepackage[margin=0.7in]{geometry}
#+AUTHOR: %%AUTHOR%% | %%STDID%%

#+DATE: due: January 28^{rd}, 2022
#+LaTeX_HEADER: \usepackage{lastpage}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{bbm}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \chead{} %%AUTHOR%%
#+LATEX_HEADER: \lhead{total pages: \pageref{LastPage}}
#+LATEX_HEADER: \rhead{this is page \thepage}
#+LATEX_HEADER: \lfoot{}
#+LATEX_HEADER: \cfoot{ECON 497 Winter 2022}
#+LATEX_HEADER: \rfoot{}
#+LATEX: \renewcommand{\footrulewidth}{0.4pt}

#+LATEX: \linespread{1.5}

* Q1
Write the model in matrix form[fn::note that I am using the more standard $(\hat\beta_0,\hat\beta_1)^T$ instead of $(\hat\beta_1,\hat\beta_2)^T$ ]:

\[y = \left(y_1, \ldots, y_n \right) = X\beta + \epsilon = \begin{pmatrix} 1      & x_1 \\ \ldots & \ldots \\ 1 & x_n \end{pmatrix} \begin{pmatrix} \beta_0 \\ \beta_1 \end{pmatrix} + \epsilon\]

** Q1a
We show that the OLS estimator $\hat\beta = (X^TX)^{-1}X^T y$
matches the SLR expresisons:

First, \[X^TX = \begin{pmatrix} \sum_1^n 1 & \sum x_i \\ \sum x_i & \sum x_i^2 \end{pmatrix} = n \begin{pmatrix} 1 & \bar{x} \\ \bar{x} & \bar{x^2} \end{pmatrix} \]

And since $\begin{pmatrix} a & b\\b & c\end{pmatrix}^{-1} = \Delta^{-1}\begin{pmatrix} c & -b \\ -b & a \end{pmatrix}$ with the determinant $\Delta := ac - b^2$, we have[fn::We use a standard convention of denoting the realized sample value of a statistic $T$ by its lowecase $t$, so e.g. $n\bar{x} := \sum{x_i}, \ n\bar{x_i^2} := \sum x_i^2$]

#+NAME: XTX
\begin{equation}
(X^T X)^{-1} = \frac{1}{n(\bar{x_i} - \bar{x}^2)} \begin{pmatrix} \bar{x^2} & -\bar{x} \\ -\bar{x} & 1\end{pmatrix}
\end{equation}

Further, \[X^T y = \begin{pmatrix}n\bar{y}\\ \sum x_i y_i\end{pmatrix}\]
So that \[\hat{\beta} = \begin{pmatrix} \hat{\beta_0} \\ \hat{\beta_1} \end{pmatrix} = \Delta^{-1} \begin{pmatrix}n\bar{y}\bar{x^2} - \bar{x}\sum{x_i y_i} \\ \sum x_i y_i - n\bar{x}\bar{y}\end{pmatrix} = \frac{1}{n(\bar{x^2}-\bar{x}^2)}\begin{pmatrix}n\bar{y}\bar{x^2} - \bar{x}\sum{x_i y_i} \\ \sum x_i y_i - n\bar{x}\bar{y}\end{pmatrix} \]

Simple rearrangement will yield for the denominator
#+NAME: beta-denominator
\begin{equation}
\sum(x_i-\bar{x})^2 = \sum x_i^2 - 2\bar{x}\sum{x_i} + n\bar{x}^2 = n(\bar{x^2} - \bar{x}^2)
\end{equation}

Furthermore, by centralizing $u_i := x_i - \bar{x},\ v_i := y_i - \bar{y}$ so that $\bar{u} = \bar{v} = 0$, we have \[\sum u_i v_i = \sum(x_i - \bar{x})(y_i - \bar{y}) = \sum u_i (y_i - \bar{y}) = \sum u_i y_i - n\bar{u}\bar{y} = \sum x_i y_i - n\bar{x}\bar{y} \]
Together, the two expressions above mean we have derived $\hat{\beta_1}$ in the desired form: \[\hat{\beta_1} = \frac{\sum x_i y_i - n\bar{x}\bar{y}}{n(\bar{x^2} - \bar{x}^2)} = \frac{\sum(x_i-\bar{x})(y_i-\bar{y})}{\sum(x_i-\bar{x})^2}\]
So that \[\hat{\beta_0} = \frac{n\bar{y}\bar{x^2} - \bar{x}\sum{x_i y_i}}{n(\bar{x^2} - \bar{x}^2)} = -\bar{x} \frac{\sum x_i y_i - n \bar{x}\bar{y}}{n(\bar{x^2}-\bar{x}^2)} + \frac{n\bar{y}\bar{x^2}-n\bar{x}^2\bar{y}}{n(\bar{x^2} - \bar{x}^2)} = \bar{y} - \hat{\beta_1}\bar{x}\]

** Q1b
Equations [[XTX]] and [[beta-denominator]] together yield immediately
\[\frac{\mathbbm{V}[\hat{\beta_0}]}{\sigma^2} = \frac{\bar{x^2}}{\sum (x_i - \bar{x})^2}\] and
\[\frac{\mathbbm{V}[\hat{\beta_1}]}{\sigma^2} = \frac{1}{\sum(x_i-\bar{x})^2}
\]

* Q2
Model: \[y = X\beta + \epsilon = X \begin{pmatrix}\beta_1\\ \beta_2 \\ \beta_3 \\ \beta_4\end{pmatrix} + \epsilon\]
Null hypothesis: $H_0: \beta_2 = \beta_2$, alterntive $H_a: \beta_2 \neq 0$ or $\beta_3 \neq 0$.
** Q2a
In matrix form, $H_0$ is written as \[\begin{pmatrix}0 & 1 & 0& 0\\ 0 & 0 & 1 & 0 \end{pmatrix} \begin{pmatrix}\beta_1 \\ \beta_2 \\ \beta_3 \\ \beta_4 \end{pmatrix} = \begin{pmatrix}0\\ 0\end{pmatrix}\]
Under $H_0$, the statistic \[F := \frac{(R\hat{\beta})^T[R(X^T X)R^T]^{-1}(R\hat{\beta})/2}{SSR/(n-4)} = \frac{(RSS_r - RSS_{ur})/2}{RSS/(n-4)}\]
is distributed as $F^2_{n-4}$.
** Q2b
The statistic \[F = \frac{(RSS_r - RSS_{ur})/q}{RSS_{ur}/(n-k)}\] is $F^q_{n-k}$-distributed.
In this example, $n=104, k=4, q=2, RSS_r = 86, RSS_{ur}=79$. Subsitute to obtain the value of the F-statistic \[F = 4.430\]
The critical value at 5% significance, however[fn::see Appendix for R code], is $F^* = 3.087 < 4.430$, so that we reject the null hypothesis; the restriction of the model is not supported by the sample.
** Q2c
In matrix form, $H_0$ is written as \[\begin{pmatrix}0 & 1 & 0& -1\\ 0 & 0 & 1 & 0 \end{pmatrix} \begin{pmatrix}\beta_1 \\ \beta_2 \\ \beta_3 \\ \beta_4 \end{pmatrix} = \begin{pmatrix}3\\ 0\end{pmatrix}\]
* Q3
\begin{equation*}
\begin{aligned}
\hat{\mu_1} &:= \frac{1}{n-5}\sum_1^n x_i \\
\hat{\mu_2} &:= \alpha \frac{\sum_1^k x_i}{k} + \beta \frac{\sum_{k+1}^n x_i}{n-k}
\end{aligned}
\end{equation*}
with $0 < k < n$, $0 < \alpha,\beta < 1$, $\alpha + \beta = 1$. Here, $\alpha = \frac{1}{3} = 1-\beta$, $k=1$.

** TL;DR
| estimator $\hat{\mu}$ \ properties | $E[\hat{\mu}]$     | $V[\hat{\mu}]/\sigma^2$                                            | unbiased? | BLUE       | p-$\lim$        | consistent? |
|------------------------------------+--------------------+--------------------------------------------------------------------+-----------+------------+-----------------+-------------|
| $\hat{\mu_1}$                      | $\frac{n}{n-5}\mu$ | $\left(\frac{n-5}{n}\right)^2$                                     | *no*      | no; biased | $\delta(x-\mu)$ | yes         |
| $\hat{\mu_2}$                      | $\mu$              | $\frac{\alpha^2}{k} + \frac{\beta^2}{n-k} \geq \frac{\alpha^2}{k}$ | yes       | no         |                 | *no*        |

* Q4
a. The regression coefficients are given in the table below, the code and R output are in the Appendix
   | model ($j=$) | intercept $\alpha_j$ | $\beta_j$ | $R^2$ |
   |--------------+----------------------+-----------+-------|
   |            1 |                0.246 |     1.112 | 0.610 |
   |           10 |              -0.0330 |     0.928 | 0.946 |
b. The coefficients $\beta$ here measure how closely the portfolo performance track the market as a whole; we see that the smaller-capitalization stock portfolio has greater relative gains and losses than the market average, whereas the large-cap portfolio has smaller.
c. The $R^2$ gives a measure of how much of the variability of the regressand is explained by the variability of the regressor. In this example, we see that model 1 has relatively low $R^2$, indicating greater volatility in the low-cap segment, especially compared with the 'blue-chip' segment with its high value of $R^2$. However, we must be wary of selection bias here: there are fewer high-cap stocks than low-cap, which means that most major indices, as well as the market proxy /rmrf/ we are using, will include the /d10/ portfolio; on the other hand, not many members of the /d1/ portfolio are likely to be included in /rmrf/. Near-perfect $R^2$ of model 10 could therefore be an artefact.
d. The t-statistic \[t := \frac{\beta - \hat{\beta}}{se(\beta)}\]
   is distributed as $t_{n-1}$ provided $\hat{\beta}$ is normally distributed, $se^2(\beta)$ is $\chi^2_{n-1}$.
* Appendix - R code
\tiny
** Q2
#+begin_example
> qf(0.95,df1=2,df2=100)
[1] 3.087296
#+end_example
** Q4
#+begin_example
> assets <- read.csv('assets.csv')

> assets['r1'] <- assets['d1'] - assets['rf']
> assets['r10'] <- assets['d10'] - assets['rf']
> lm1 <- lm(r1 ~ rmrf, data = assets)
> lm10 <- lm(r10 ~ rmrf, data = assets)

> summary(lm1)

Call:
lm(formula = r1 ~ rmrf, data = assets)

Residuals:
     Min       1Q   Median       3Q      Max
-16.5835  -2.4291  -0.1376   1.8861  25.8655

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  0.24583    0.16316   1.507    0.132
rmrf         1.11223    0.03602  30.880   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.017 on 610 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.6099,    Adjusted R-squared:  0.6092
F-statistic: 953.6 on 1 and 610 DF,  p-value: < 2.2e-16

> summary(lm10)

Call:
lm(formula = r10 ~ rmrf, data = assets)

Residuals:
    Min      1Q  Median      3Q     Max
-5.5580 -0.5735  0.0090  0.6221  5.6962

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) -0.033040   0.040662  -0.813    0.417
rmrf         0.927640   0.008976 103.346   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 1.001 on 610 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.946,     Adjusted R-squared:  0.9459
F-statistic: 1.068e+04 on 1 and 610 DF,  p-value: < 2.2e-16

#+end_example
